### ISSUE TITLE
App does not compile

### ISSUE THREAD

**Issue by martindlarsson** [danneu/elm-app#1]
Thanks for creating this package!

The app is not compiling on my computer. I installed the package (0.0.7) globally and ran `elm-app init appname`, jumped into the directory and ran `elm-app start`.

This is what the error message looks like:

```
ERROR in [tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/index.js main[2]

ERROR in ./src/index.js
Module build failed (from /usr/local/lib/node_modules/elm-app/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
```

**Comment by danneu** [comment]
Thanks, I realize tsconfig.json wasn't being packaged when publishing to npm.

I published an update to npm: https://github.com/danneu/elm-app/commit/de28c2b794db6447572eb1c13f4cf18d8de045bf

Though I find it hard to test npm packages locally since, like in this case, they may accidentally work due to files that exist in my dev env and not for anybody else.

Definitely use https://github.com/halfzebra/create-elm-app instead of this tool though for serious projects.

**Comment by martindlarsson** [comment]
Yay, now it compiles. Thanks!
